### PR TITLE
Use NullFileProvider from FileSystem

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Reacting to https://github.com/aspnet/FileSystem/pull/175

### CODE REVIEW

**Comment by moozzyk** [comment]
LGTM

**Comment by davidfowl** [comment]
> "Microsoft.Extensions.FileProviders.Null": "1.0.0-*",

Is that really a package name lolz :smile:

**Comment by Eilon** [comment]
@davidfowl definitely not, I commented on that in the FileSystem repo.

**Comment by JunTaoLuo** [comment]
After we decide a name for the package I will update this.

**Pull request merged**
