### PR TITLE
 Change SelfHostDeployer to use dynamic ports by default (#1383)

### PR DESCRIPTION
**Pull request by pranavkm**
* Should significantly reduce flaky test failures due to AddressInUse exceptions
* Addresses https://github.com/aspnet/Hosting/issues/1296

### CODE REVIEW

**Comment by pranavkm** [comment]
Porting to 2.1 to improve test reliability. See https://github.com/aspnet/MvcPrecompilation/issues/292

**Comment by Tratcher** [comment]
Link to the prior work item/commit you're backporting?

**Comment by pranavkm** [comment]
PR: https://github.com/aspnet/Hosting/pull/1383/files

**Comment by pranavkm** [comment]
@mkArtakMSFT could you do a shiproom notification for this? Change is in the 2.1 branch and this is a change in non-shipping test only package that improves stability.

**Pull request merged**
