### PR TITLE
Make dotnet publish use LogInformation instead of LogTrace

### PR DESCRIPTION
**Pull request by pranavkm**
This would make it have the same LogLevel as dotnet run so we'd have better diagnostics without having to change tests.

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Tratcher \ @kichalla 

Most tests set the LogLevel to Information:

* https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/PublishAndRunTests.cs#L78
* https://github.com/aspnet/Entropy/blob/dev/test/FunctionalTests/TestServices.cs#L39

which means we (a) it looks like the test is hanging while it publishes (b) we don't get detailed publish logs by default.

**Comment by Tratcher** [comment]
We intentionally lowered the level of some of these items to reduce log spam.
- How long does publish take?
- How much output does it generate?

**Comment by pranavkm** [comment]
Here's the output for MusicStore:

```
Publishing MusicStore for .NETCoreApp,Version=v1.0
Project MusicStore (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Configuring the following project for use with IIS: 'D:\work\katana\MusicStore\samples\MusicStore\bin\Debug\netcoreapp1.0\publish'
Updating web.config at 'D:\work\katana\MusicStore\samples\MusicStore\bin\Debug\netcoreapp1.0\publish\web.config'
Configuring project completed successfully
publish: Published to D:\work\katana\MusicStore\samples\MusicStore\bin\Debug\netcoreapp1.0\publish
Published 1/1 projects successfully
```

It takes about 2.5 seconds on netcoreapp1.0 and about 1.5 on desktop. Doesn't seem super noisy.

**Comment by Tratcher** [comment]
A 2.5 second pause makes you think it hung?

**Comment by pranavkm** [comment]
In precompilation's case, this tends to be a lot longer (~5-6 seconds). Plus it's not about the pause in itself. The log prints spews from our tools, so it's pretty useful to diagnose in case they run in to issues.

**Comment by Tratcher** [comment]
:shipit:

**Pull request merged**
