### PR TITLE
Rename environment variables to ASPNETCORE_. 

### PR DESCRIPTION
**Pull request by Tratcher**
Also remove the legacy ENV abbreviation.
@DamianEdwards @davidfowl @muratg @JunTaoLuo @BillHiebert

### CODE REVIEW

**Comment by BillHiebert** [comment]
@Tratcher - do you still support the old variables? ie. will we be broken when we pick up this change?

**Comment by davidfowl** [comment]
Yes you'll be broken.

Make sure you write an announcement

**Comment by Tratcher** [comment]
Correct, we're not supporting the old variables this time.

**Comment by muratg** [comment]
:shipit:

**Comment by muratg** [comment]
@Tratcher Announcement issue?

**Comment by cwe1ss** [comment]
Could you please also update and/or add a comment to https://github.com/aspnet/Announcements/issues/108 which contains the table with all new names.

**Comment by Tratcher** [comment]
Commented.

**Pull request merged**
