### PR TITLE
Prevent NullReferenceException when disposing Context.Scope (#782).

### PR DESCRIPTION
**Pull request by cesarbs**
#782 

cc @Tratcher

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
should we add a test?

**Comment by cesarbs** [comment]
@JunTaoLuo Done.

**Comment by JunTaoLuo** [comment]
:shipit:

**Comment by cesarbs** [comment]
Fixed in https://github.com/aspnet/Hosting/commit/0f79bff98b2621562e3336c06ecce79be2b29a9d.

**Pull request closed without merging**
