### PR TITLE
Remove references to IRuntimeEnvironment \ IApplicationEnvironment

### PR DESCRIPTION
**Pull request by pranavkm**
cc @DamianEdwards \ @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
You missed some in WebHostBuilder

**Comment by pranavkm** [comment]
Not seeing any in `WebHostBuilder`? What am I missing?

**Comment by davidfowl** [comment]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L177

**Comment by pranavkm** [comment]
Updated

**Pull request merged**
