### PR TITLE
OwinFeature collection throws NotSupported exception as the featurecolle...

### PR DESCRIPTION
**Pull request by Praburaj**
...ction is immutable

Addresses: https://github.com/aspnet/HttpAbstractions/issues/207

@borgdylan @Tratcher

### CODE REVIEW

**Comment by Praburaj** [comment]
Will update the PR with a test.

**Comment by davidfowl** [comment]
:shipit:

**Comment by borgdylan** [comment]
Will test as soon as it is shipped

**Comment by Praburaj** [comment]
Added a test to cover the `OwinFeatureCollection` scenario.

**Comment by Praburaj** [comment]
@davidfowl signed off on this while at my office. Merging the change in.

**Pull request merged**
