### PR TITLE
Porting "Always log startup exceptions" to 1.0.6

### PR DESCRIPTION
**Pull request by jkotalik**
Fix for https://github.com/aspnet/Hosting/issues/1159.
@pranavkm I was running into errors when I ran build.cmd from scratch. Said I didn't have the 1.0.5 runtime installed even though I did.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Ditto, make sure you create rel/1.0.4 branch for this patch.

**Comment by pranavkm** [comment]
Odd - let me have a look.

**Comment by jkotalik** [comment]
Closing in favor of 1.0.4

**Comment by pranavkm** [comment]
Try it now (with a `git clean`).

**Pull request closed without merging**
