### PR TITLE
Add serviceable attribute to projects.

### PR DESCRIPTION
**Pull request by NTaylorMullen**

### CODE REVIEW

**Comment by Eilon** [comment]
Missing the https://github.com/aspnet/Hosting/tree/dev/src/Microsoft.AspNet.Hosting.Server.Interfaces project?

**Comment by NTaylorMullen** [comment]
@Eilon doesn't exist in release.

**Comment by Eilon** [comment]
Ah OK :smile:

**Comment by NTaylorMullen** [comment]
Updated.

**Comment by Eilon** [comment]
What did you update? Though, we do need a change for just dev to add the new assembly.

**Comment by NTaylorMullen** [comment]
lol trigger finger paste is all :smile:

**Comment by Eilon** [comment]
OK :smile:

**Comment by NTaylorMullen** [comment]
:shipit:

**Pull request merged**
