### PR TITLE
Add tests for map path without wwwroot, and typos

### PR DESCRIPTION
**Pull request by pakrym**
@victorhurdugaci @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
Add another test that makes sure there's a 404 when the webroot isn't set.

**Comment by Tratcher** [comment]
You'd need to put that test in StaticFiles.

**Comment by pakrym** [comment]
https://github.com/aspnet/StaticFiles/pull/87

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
