### PR TITLE
Hosting API review # 2

### PR DESCRIPTION
**Pull request by Praburaj**
1. Moving HostingUtilities and PipelineInstance into internal namespaces.
2. Renaming some properties in IHostingEnvironment
3. Renaming IHttpContextAccessor HttpContext into Value.

Addresses:
https://github.com/aspnet/Hosting/issues/159
https://github.com/aspnet/Hosting/issues/157
https://github.com/aspnet/Hosting/issues/161

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit:

**Comment by davidfowl** [comment]
Wasn;t it supposed to be IHttpContextAccessor.HttpContext?

**Comment by Eilon** [comment]
Oh that sounds right, I missed that.

**Comment by Praburaj** [comment]
My bad. I typed that by mistake. Actually this PR does not have fix for that bug.

**Pull request merged**
