### PR TITLE
Remove TestProjectHelpers from Server.IntegrationTesting

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses #994.

### CODE REVIEW

**Comment by Tratcher** [comment]
Almost exactly the same code exists in several functional test projects like https://github.com/aspnet/ServerTests/blob/dev/test/ServerComparison.FunctionalTests/Helpers.cs#L12. How about generalizing this rather than removing it?

**Comment by JunTaoLuo** [comment]
Move to Testing? I think that makes more sense than Common.

**Comment by Tratcher** [comment]
Makes sense

**Comment by JunTaoLuo** [comment]
:up::date:

**Pull request merged**
