### PR TITLE
[Proposal] Lazy requestId and move TraceIdentifier to HttpAbstractions

### PR DESCRIPTION
**Pull request by benaadams**
Requires https://github.com/aspnet/HttpAbstractions/pull/440
Resolves https://github.com/aspnet/Hosting/issues/392

### CODE REVIEW

**Comment by benaadams** [comment]
Change, now requires #435 instead

**Comment by benaadams** [comment]
Required PR is now https://github.com/aspnet/HttpAbstractions/pull/440

**Comment by Tratcher** [comment]
This heavily overlaps https://github.com/aspnet/Hosting/pull/403. I recommend having @lodejard merge this into his PR.

**Comment by benaadams** [comment]
Added clean up part to #409 as a merge to #403 other part it going different way; left comments for that. 

Closing.

**Pull request closed without merging**
