### PR TITLE
Only wrap readonly IFeatureCollections

### PR DESCRIPTION
**Pull request by benaadams**
Perf improvement suggested by @Tratcher in https://github.com/aspnet/Hosting/issues/310 also needed to full take advantage of Kestrel's feature collection improvements coming down the pipe.

### CODE REVIEW

**Comment by Tratcher** [comment]
Ok @benaadams, you can remove the wrapper completely.

**Comment by benaadams** [comment]
Done

**Comment by benaadams** [comment]
I need to change some tests?

**Comment by benaadams** [comment]
Uncomfortable with the test change

**Comment by davidfowl** [comment]
We need to fix the owing feature collection

**Comment by benaadams** [comment]
There is a lot of angry in the tests, trying to get to bottom of it, but can't run them locally

**Comment by benaadams** [comment]
Highlights for items where entire point of test is now bypassed:

https://github.com/benaadams/Hosting/blob/only-wrap-readonly-features/test/Microsoft.AspNet.Hosting.Tests/HostingEngineTests.cs#L322

https://github.com/benaadams/Hosting/blob/only-wrap-readonly-features/test/Microsoft.AspNet.Hosting.Tests/HttpContextFactoryFacts.cs#L19

**Comment by benaadams** [comment]
They are bypassed by wrapping with ```FeatureCollection``` so may be desired outcome?

**Comment by davidfowl** [comment]
@Tratcher assigning this one to you. We should merge this in when the servers support it. We probably need to update the OwinFeatureCollection as well?

**Comment by Tratcher** [comment]
Done. Filed a separate issue for the OwinFeatureCollection: https://github.com/aspnet/HttpAbstractions/issues/431

**Comment by Tratcher** [comment]
FYI: The servers already supported it.

**Comment by borgdylan** [comment]
As things stand owinfeaturecollection is still read-only yet it is no longer being wrapped. This makes all requests fail.

**Pull request closed without merging**
