### PR TITLE
Rename Microsoft.AspNet.Hosting.json to hosting.json.

### PR DESCRIPTION
**Pull request by Tratcher**
#452 @davidfowl @muratg @Eilon @DamianEdwards 

@davidfowl  want's this for RC1.

### CODE REVIEW

**Comment by davidfowl** [comment]
The people have spoken!

**Comment by davidfowl** [comment]
Why is the build failing :smile:

**Comment by Tratcher** [comment]
Travis can't restore dependencies right now...

**Comment by davidfowl** [comment]
Spoke to @pranavkm :shipit:

**Pull request merged**
