### PR TITLE
Make webHostBuilder.UseStartup(startupAssemblyName) work

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by Tratcher** [comment]
Care to add a test or two?

**Comment by bricelam** [comment]
Sure. But now I wish I would have just filed a bug... :wink:

**Comment by Tratcher** [comment]
Feel free :-)

**Comment by bricelam** [comment]
Added a unit test.

**Comment by Tratcher** [comment]
:shipit:

**Pull request merged**
