### PR TITLE
Remove dnx451 and dnxcore50 TFM's

### PR DESCRIPTION
**Pull request by henkmollema**
#531

### CODE REVIEW

**Comment by henkmollema** [comment]
Looks like the new `Microsoft.Extensions.Options` package is not pushed to the CI feed yet.

**Comment by HaoK** [comment]
What's still broken?  I thought it was just coherence waiting for builds to complete in a row. All the repos were green individually yesterday :/

**Comment by davidfowl** [comment]
@HaoK I made a change to the Options repo to fix it. It was just older package versions.

**Pull request merged**
