### PR TITLE
Add infrastructure to analyze the middleware pipeline.

### PR DESCRIPTION
**Pull request by Tratcher**
#318 @avanderhoorn @davidfowl @lodejard 
Also:
https://github.com/aspnet/Entropy/commit/0a003940338a641f1a93659d4b79de661da7a3d7
https://github.com/aspnet/HttpAbstractions/commit/162005aa761874a130855bbbc2ef8344a1f95dbe

Initial PR to verify design. Still needs docs and tests.

Output from the entropy sample:
```
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/map/foo
MiddlewareStarting: RequestServicesContainerMiddleware; /map/foo
MiddlewareStarting: IISPlatformHandlerMiddleware; /map/foo
MiddlewareStarting: UseInlineMiddleware; /map/foo
MiddlewareStarting: DefaultFilesMiddleware; /map/foo
MiddlewareStarting: DirectoryBrowserMiddleware; /map/foo
MiddlewareStarting: Diagnostics.Middleware.Analysis.Startup+<>c; /map/foo
MiddlewareStarting: RenamedStaticFiles; /map/foo
verb: Microsoft.AspNet.StaticFiles.StaticFileMiddleware[4]
      The request path /map/foo does not match a supported file type
MiddlewareStarting: MapMiddleware; /map/foo
MiddlewareStarting: RunInlineMiddleware; /foo
MiddlewareFinished: RunInlineMiddleware; 200
MiddlewareFinished: MapMiddleware; 200
MiddlewareFinished: RenamedStaticFiles; 200
MiddlewareFinished: Diagnostics.Middleware.Analysis.Startup+<>c; 200
MiddlewareFinished: DirectoryBrowserMiddleware; 200
MiddlewareFinished: DefaultFilesMiddleware; 200
MiddlewareFinished: UseInlineMiddleware; 200
MiddlewareFinished: IISPlatformHandlerMiddleware; 200
MiddlewareFinished: RequestServicesContainerMiddleware; 200
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0078ms 200
```

### CODE REVIEW

**Comment by davidfowl** [comment]
His shouldn't be in by default. This is just a design or right?

**Comment by Tratcher** [comment]
It's not enabled by default, you have to enable it with `services.AddMiddlewareAnalysis();`. https://github.com/aspnet/Entropy/commit/0a003940338a641f1a93659d4b79de661da7a3d7#diff-9f226b9022c280befddc97d32f23dd8fR17
Or were you saying it should be in a separate package?

**Comment by davidfowl** [comment]
Separate package in the diagnostics repo

**Comment by Tratcher** [comment]
Sure, this hosting stuff can all move to diagnostics with two provisions: 1. It still needs a hosting dependency for IStartupFilter, and 2. I want to leave the http.abstractions stuff where it is so that everyone can get to it without the extra dependency.

**Comment by davidfowl** [comment]
It really doesn't belong in HttpAbstractions though.

**Comment by Tratcher** [comment]
Moving to diagnostics.

**Pull request closed without merging**
