### PR TITLE
Fix Logged elapsed time

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/aspnet/Hosting/issues/478

### CODE REVIEW

**Comment by Tratcher** [comment]
@sebastienros

**Comment by JunTaoLuo** [comment]
Verified that `Environment.TickCount` is always in milliseconds on Windows/Linux/Mac across clr/coreclr/mono. :shipit: from me. Note that this will mean that our logging of elapsed time will remain at the millisecond resolution. @sebastienros

**Comment by sebastienros** [comment]
It more than the millisecond, the documentation states that it's in the order of 10ms.
But :shipit:

**Comment by JunTaoLuo** [comment]
actually why are we not using `TimeSpan.FromMilliseconds`?

**Comment by sebastienros** [comment]
I think you are confused, or you confused me.

**Comment by JunTaoLuo** [comment]
Actually using `new Timespan(<long>)` 10x times faster than `TimeSpan.FromMilliseconds(<double>)` so the current implementation is good.

**Comment by JunTaoLuo** [comment]
Going to close and reopen to trigger the cla bot

**Comment by JunTaoLuo** [comment]
merged to dev

**Comment by benaadams** [comment]
@JunTaoLuo added PR for sub-millisecond timings: "Higher accuracy in timings" #543

**Pull request closed without merging**
