### PR TITLE
Cleanup for HttpAbstractions changes

### PR DESCRIPTION
**Pull request by benaadams**
Merge RequestIdentifier cleanup from #394 from HttpAbstraction changes

As suggested by @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit: @lodejard

**Comment by benaadams** [comment]
Other changes required are in comments for  #403

**Comment by benaadams** [comment]
Fixed broken test using aspnetvolatiledev

**Comment by benaadams** [comment]
Still issues with Coherence and HttpAbstractions; though not entirely sure what that means :)

**Comment by Tratcher** [comment]
@benaadams :-) Our CI that verifies packages from aspnetvolatiledev and pushes them to aspnetcidev has been broken all day.

**Comment by benaadams** [comment]
Working now :dancer:

**Comment by benaadams** [comment]
Resolved

**Pull request closed without merging**
