### PR TITLE
Change Certificates.Configuration to a Sources package

### PR DESCRIPTION
**Pull request by Tratcher**
This only has internal consumers.

Fixes https://github.com/aspnet/Hosting/issues/1098

### CODE REVIEW

**Comment by davidfowl** [comment]
Shouldn't this go into Common with the rest of the source packages?

**Comment by Tratcher** [comment]
It can't be tested in common, it needs Logging and Configuration.

**Comment by davidfowl** [comment]
Ugh this is so arbitrary.

**Comment by Tratcher** [comment]
The other idea was to put it in Kestrel's repo so it's at least next to one of its consumers. We've done something similar for StaticFiles & MVC

**Comment by Tratcher** [comment]
Note types need to be made internal now.

**Comment by Tratcher** [comment]
Will rebase onto rel/2.0.0-preview2 before committing

**Comment by Tratcher** [comment]
Merged to rel and dev.

**Pull request closed without merging**
