### PR TITLE
Removed PublishApplicationBeforeDeployment from DeploymentParameters

### PR DESCRIPTION
**Pull request by kichalla**
@JunTaoLuo @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
Why?

**Comment by kichalla** [comment]
> Why?

Do we plan to support this in future? Currently we set to `true` everywhere this is used, no?

**Comment by Tratcher** [comment]
It wasn't true by default for self-host, only IIS/Express.

**Comment by kichalla** [comment]
:+1: Seems like in MusicStore its true for all types of server, but not in case of ServerTests.I will leave it as it is then (but I would prefer the publish approach as it seems more like a production scenario)

**Pull request closed without merging**
