### PR TITLE
Print the application base path out

### PR DESCRIPTION
**Pull request by davidfowl**
- This helps to show how the host is configured

/cc @Tratcher @JunTaoLuo

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
:shipit: Yikes travis is so broken.

**Comment by davidfowl** [comment]
Looking at @NTaylorMullen :imp:. Coherence has been down all weekend...

**Comment by Tratcher** [comment]
I think this crosses from friendly startup information to debug output. Why not log it instead? Loggers should be available at this point.

**Comment by davidfowl** [comment]
@Tratcher it's part of the relevant configuration for a web application. It's relevant for things like the wwwroot, and for mvc the views folder. Not sure why this would be verbose.

**Comment by Tratcher** [comment]
The server addresses and shutdown message are actionable.  ApplicationBasePath is only displayed for diagnostic purposes. Diagnostics should be written to Logging so you can control the signal-to-noise ratio.

**Comment by davidfowl** [comment]
> ApplicationBasePath is only displayed for diagnostic purposes. Diagnostics should be written to Logging so you can control the signal-to-noise ratio.

Just like the environment? I think the argument is weak. Everything printed in for diagnostics, this is no different.

**Pull request merged**
