### PR TITLE
Target netstandard1.3

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @benaadams \ @halter73

**Comment by pranavkm** [comment]
FYI @Eilon

**Comment by benaadams** [comment]
Is it just `Microsoft.AspNetCore.Diagnostics` that needs the version check?

**Comment by pranavkm** [comment]
No, we fixed the package in Common so that it can target `netstandard1.3`. I'm going to update the lot.

**Pull request merged**
